App\Domain\UnitOfProduct\Entity\UnitOfProduct:
  type: entity
  fields:
    id:
      id: true
      type: uuid
    createdAt:
      type: datetime_immutable
    updatedAt:
      type: datetime_immutable
      nullable: true
    status:
      type: string
    isAvailable:
      type: boolean
  manyToOne:
    product:
      targetEntity: App\Domain\Product\Entity\Product
      inversedBy: units
      joinColumn:
        name: product_id
        referencedColumnName: id
