doctrine:
    dbal:
        charset: utf8
        driver: pdo_pgsql
        server_version: 11
        user: '%env(resolve:PSQL_USER)%'
        password: '%env(resolve:PSQL_PASS)%'
        dbname: '%env(resolve:PSQL_DATABASE)%'
        host: '%env(resolve:PSQL_HOST)%'
        port: '%env(resolve:PSQL_PORT)%'
        types:
            uuid: Ramsey/Uuid/Doctrine/UuidType
            money: App\Domain\Common\Type\MoneyType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
          user:
            is_bundle: false
            type: yml
            prefix: 'App\Domain\User\Entity'
            dir: '%kernel.project_dir%/config/mapping/user'
          balanceOperation:
            is_bundle: false
            type: yml
            prefix: 'App\Domain\Balance\Entity'
            dir: '%kernel.project_dir%/config/mapping/balance'
          category:
            is_bundle: false
            type: yml
            prefix: 'App\Domain\Category\Entity'
            dir: '%kernel.project_dir%/config/mapping/category'
          product:
            is_bundle: false
            type: yml
            prefix: 'App\Domain\Product\Entity'
            dir: '%kernel.project_dir%/config/mapping/product'
          unitOfProduct:
            is_bundle: false
            type: yml
            prefix: 'App\Domain\UnitOfProduct\Entity'
            dir: '%kernel.project_dir%/config/mapping/unitOfProduct'
          cartItem:
            is_bundle: false
            type: yml
            prefix: 'App\Domain\CartItem\Entity'
            dir: '%kernel.project_dir%/config/mapping/cartItem'
          unitOperation:
            is_bundle: false
            type: yml
            prefix: 'App\Domain\UnitOperation\Entity'
            dir: '%kernel.project_dir%/config/mapping/unitOperation'
