services:
  _defaults:
    autowire: true
    autoconfigure: true

  security.user.user_provider:
    class: App\Application\Security\UserProvider
    autowire: true

  security.firewall.access_denied_handler:
    class: App\Application\Security\AccessDeniedHandler

security:
    encoders:
      App\Application\Security\UserAdapter:
        algorithm: bcrypt

    providers:
      custom_user_provider:
        id: security.user.user_provider

    firewalls:
        auth_management:
          pattern: ^/auth
          anonymous: true
          stateless: true

        api:
          pattern: ^/(?!auth)
          anonymous: false
          stateless: true
          provider: custom_user_provider
          access_denied_handler: security.firewall.access_denied_handler
          guard:
            authenticators:
              - lexik_jwt_authentication.jwt_token_authenticator
