App\Domain\User\Entity\User:
  type: entity
  inheritanceType: JOINED
  discriminatorColumn:
    name: type
    type: string
  discriminatorMap:
    admin: App\Domain\User\Entity\Admin
    client: App\Domain\User\Entity\Client
  embedded:
    contact:
      class: App\Domain\User\Entity\Contact
      columnPrefix: false
    auth:
      class: App\Domain\User\Entity\Auth
      columnPrefix: false
    activity:
      class: App\Domain\User\Entity\Activity
      columnPrefix: false
  fields:
    id:
      id: true
      type: uuid
