services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  http.listener.json_response:
    class: App\Infrastructure\Http\Listener\JsonResponseListener
    tags:
      - { name: kernel.event_listener, event: kernel.view, method: handle }

  http.listener.serializable_exception:
    class: App\Infrastructure\Http\Listener\SerializableExceptionListener
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: handle }

  http.listener.validation_exception:
    class: App\Infrastructure\Http\Listener\ValidationExceptionListener
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: handle }

  http.listener.jwt_expired_token:
    class: App\Infrastructure\Http\Listener\Jwt\JwtExpiredListener
    tags:
      - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_expired, method: handle }

  http.listener.jwt_invalid_token:
    class: App\Infrastructure\Http\Listener\Jwt\JwtNotValidListener
    tags:
      - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_invalid, method: handle }

  http.listener.jwt_token_not_found:
    class: App\Infrastructure\Http\Listener\Jwt\JwtNotFoundListener
    tags:
      - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_not_found, method: handle }