admin:
  resource: '../src/Application/Http/Admin/'
  type: annotation
  prefix: '/admin'

lexik_jwt_login:
  path: /auth/login

gesdinet_jwt_refresh_token:
  path:       /auth/token/refresh
  controller: gesdinet.jwtrefreshtoken::refresh

app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

