App\Domain\Product\Entity\Product:
  type: entity
  fields:
    id:
      id: true
      type: uuid
    price:
      type: money
    createdAt:
      type: datetime_immutable
    updatedAt:
      type: datetime_immutable
      nullable: true
    isAvailable:
      type: boolean
  embedded:
    content:
      class: App\Domain\Product\Entity\ProductContent
      columnPrefix: false
  manyToOne:
    addedBy:
      targetEntity: App\Domain\User\Entity\Admin
      joinColumn: added_by
      referencedColumnName: id
  oneToMany:
    units:
      targetEntity: App\Domain\UnitOfProduct\Entity\UnitOfProduct
      mappedBy: product
      cascade: ["persist", "remove"]
  manyToMany:
    categories:
      targetEntity: App\Domain\Category\Entity\Category
      cascade: ["persist"]
      joinTable:
        name: product_category
        joinColumns:
          product_id:
            referencedColumnName: id
        inverseJoinColumns:
          category_id:
            referencedColumnName: id
